name: Build APK

env:
  APKTOOL_VER: 2.9.3

on:
  push:
    branches: 
      - lineage-21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        java-version: '11'

    - uses: robinraju/release-downloader@v1.9
      with:
        repository: 'iBotPeaches/Apktool'
        tag: 'v${{ env.APKTOOL_VER }}'
        fileName: 'apktool_${{ env.APKTOOL_VER }}.jar'

    - run: java -jar apktool_${{ env.APKTOOL_VER }}.jar b .

    - uses: actions/upload-artifact@v4
      with:
        name: APK
        path: dist/ImsService.apk
